### ISSUE TITLE
Future of black-screen

### ISSUE THREAD

**Issue by haoyangnz** [railsware/black-screen#1006]
I just want to discuss about the future of black-screen.

I really like the project and would love to contribute to it, but I have some concerns.

I feel the whole project is too monolithic. It's both a terminal emulator and an interactive shell, not to mention its lack of a plugin eco-system.

I fear that this approach is only good for the short term where setup is easy, but in the longer term the project will become stale due to the lack of community.

Is there any possibility that we may split this project into the terminal emulator and a number of plugins?

Also there's hyper.js. Maybe we can even just convert this to some hyper plugins?

Would love to hear your thoughts!

**Comment by drew-gross** [comment]
There is a plugin architecture in place, just no way to load plugins, and all plugins live in the source tree. Making user loadable plugins is definitely an important feature, if you want to help. It would require some reworking of the build system to some degree, to make plugins actually be loadable, and installable at runtime, and we would also need to nail down the exact API we want for plugins. This is fairly difficult due to backwards compatibility concerns as well as the fact that the plugins use react, and we may want to be able to upgrade React versions without needing to change the plugins.

Personally I think one of the biggest strengths of black-screen is that the shell and terminal emulator are the same thing. Almost all of the cool features of black-screen would not be possible if they were separated (although having them be the same does have downsides as well) so I'm not likely to change that.

Hyper.js is cool, I'm always happy to see more approaches to a better terminal experience, but I think it's good to have multiple approaches be experimented with. The code is open source though, if you think this would be better as Hyper.js plugins you are welcome to make a fork and do that :)

**Comment by minecrawler** [comment]
>  This is fairly difficult due to backwards compatibility concerns

If you have concerns about backward compatibility, then Black-Screen should already be version 1.0.0 (as you can read on [SemVer](http://semver.org/))


> plugins use react, and we may want to be able to upgrade React

You can only upgrade React on major versions, then. Plugins will have to announce which specific Black-Screen versions they are compatible with. If there are plugins which are not compatible, display a warning and do not load them, simple as that. You really should leave stuff like, making plugins compatible with whatever technology you want to use, to the plugin authors. They have to stick to your standards to use your program, not the other way around.

**Comment by drew-gross** [comment]
In my experience, if a new version of some software doesn't work with old plugins, the plugins don't get updated, and because people like their plugins, they don't update their version of the software. This is a situation I would like to avoid.

We don't currently have compatibility concerns, but we expect to once we hit 1.0.0. We should hold off on going to 1.0.0 until we know how we are going to handle compatibility. Going to 1.0.0 without a plan will result in a mess.

**Comment by minecrawler** [comment]
In my experience, if plugin authors do not care to update their plugin, they do not care to fix bugs and hence their plugins will be a headache either way. If they don't care for their creation, it cannot be that important, to them, so why should it be to you?

I think that you can never avoid problems with plugin compatibility. That's why you should rather think about planning out major versions and sparingly do breaking changes. Collect as many breaking changes as possible over, say, a year, then merge them all at once and release the new major version. You might encourage plugin developers to use the "dev" or "master" branch to test their plugins before you release the commits to a stable branch. That way, important plugins can be made compatible from day one (especially if you communicate the release intervals well)

**Comment by drew-gross** [comment]
Not all plugins have bugs. Some are written properly from the start, and we want those to keep working.

I disagree that you can't avoid compatibility problems. I've worked on several projects that never broke backwards compatibility for any reason.

**Comment by minecrawler** [comment]
> Not all plugins have bugs

All code has bugs. Period. No matter how well written and tested a project is, it will always have bugs. Thinking otherwise would be pretty naive. The reasons are various, but mostly because things happen a developer does not expect. Time keeps flowing and all around you people create things and interact and the world changes. For example, a black-hat might find a way to use your program for remote-code-execution. That's a bug and something you might not have seen in the code and all of your pretty unit testing tools will miss it completely. It has to be fixed pronto. If a project is stale, no fixes will happen and bugs will cause problems of all kinds. What about a memory leak, which only occurs after running the program for several weeks straight (JS closures are a b*tch in that regard)? Forget about all your tests and nice code structure. If I use Black-Screen on a server, I will run into that bug. I need it fixed. There are many other types of bugs you will have a hard time finding with static analysis. Stuff you don't think about during profiling and runtime analysis. Because you are human. There will be bugs and they need to be fixed. Projects need a living community, or they die.

> I disagree that you can't avoid compatibility problems. I've worked on several projects that never broke backwards compatibility for any reason.

Sounds like you never worked on any big projects, yet. Even if your code does not break compatibility (which is stupid, because at some point, new tech arises which requires you to adapt), you were worrying about React, one of your dependencies, in the first place. Oh, and don't forget about Node.JS and Electron, which might change their API. Not breaking compatibility means you cannot upgrade to newer versions, which means that at some point, there will be no more bug fixes for your old version, which means that your project will be vulnerable to anything bad people come up with. Your only choice would be to do the fixing yourself, which is not pretty.

Do me a favor. Imagine your project in 20-30 years. How will it look? Will it still be compatible to whatever you write today? Will people still care about today's features? About today's React version? Will macOS, Windows and Linux still be the major targets?

**Comment by drew-gross** [comment]
Both Windows and Linux never break backwards compatibility and they are 2 of the largest projects in existence.

**Comment by minecrawler** [comment]
> Both Windows and Linux never break backwards compatibility and they are 2 of the largest projects in existence.

So I can play my DOS games on Windows 10? Well, I think, I have news for you...

**Comment by haoyangnz** [comment]
> Personally I think one of the biggest strengths of black-screen is that the shell and terminal emulator are the same thing. Almost all of the cool features of black-screen would not be possible if they were separated

**Comment by mizzle-mo** [comment]
I think vscode has one of the best plugin models I've seen for an Electron based app.  I've never had an extension break because of a new release and it stays fast.  I tend to stick to the bigger plugins though, so YMMV.  They see to do a really good job of avoiding/communicating breaking changes and the API is so well targeted and performance is always good.  Most changes they make are additive.

**Comment by drew-gross** [comment]
@haoyangnz one example would be how we color the background of a job red if it exits with status code != zero. Another would be how we have a button to send `SIGKILL` to a job. A third would be how we visually separate the "command line" (the part where you type text) from the job output.

@mizzle-mo I'll look into it. I think once challenge that we have is that plugins can render React components. Maybe we need to provide some extremely stable subset of the React API or something.

@minecrawler I don't have windows 10, but I have had previous versions of windows and never had any trouble running DOS programs on them. DX12 vs 9 and .NET4 vs 2 are different. Applications built against DX9 or .NET2 will continue working when you upgrade Windows. The analogy here is Black Screen : Black Screen Plugins :: Windows : Windows Applications, not Black Screen : Black Screen Plugins :: Windows Applications : DX/.NET
