### ISSUE TITLE
Implement windows version

### ISSUE THREAD

**Issue by davidabs** [railsware/black-screen#302]
I would like to work on the windows version. Where need to be changed for this purpose?
Thanks

**Comment by shockone** [comment]
Hello, @davidabs. I'm not sure I can answer that question. Perhaps, path-related things require some tweaking. Maybe pty.js won't work as expected.

More importantly, before releasing 1.0 I'd like to change the codebase not thinking about compatibility with other operating system in order to speed up the development process. I'll merge your changes but I don't promise I won't break anything.

**Comment by arcanis** [comment]
Worth noting that it could be quite interesting to be able to run Windows 10's bash from inside black-screen.

**Comment by vshatskyi** [comment]
Closing in favour of https://github.com/railsware/black-screen/issues/800
